import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./Providers";
import './globals.css'
import ModalInfo from './Common/Modal/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BetsApp F1 2024',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='' >
          <Providers>
            {children}
          </Providers>
        </div>
        <ModalInfo />
      </body>
    </html>
  )
}
